### ISSUE TITLE
await vimeoService.fetchAllVimeoVideoLinks does not work 

### ISSUE THREAD

**Issue by Joseph-Nathan** [mixin27/smf-core#1]
thanks for great package ,
await vimeoService.fetchAllVimeoVideoLinks does not work !

**Comment by mixin27** [comment]
Thanks for your issue. This package is not currently maintaining because I published it for my personal project.
But if you want to get the `vimeo` video configs, you can get by requesting `https://player.vimeo.com/video/${videoId}/config` link and parse it what you want.

If I have any personal free time later, I will continue to fix the issues. Thanks!

**Comment by mixin27** [comment]
@Joseph-Nathan Please check it out my new package [tivy](https://pub.dev/packages/tivy) for `Vimeo` and `YouTube`.
